# Generated by Django 2.2.6 on 2019-10-09 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('album', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registro',
            name='numero',
            field=models.IntegerField(),
        ),
    ]
