# Generated by Django 2.2.6 on 2019-10-09 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='cliente',
            fields=[
                ('id_c', models.AutoField(primary_key=True, serialize=False)),
                ('dni', models.CharField(max_length=50)),
                ('nombre', models.CharField(max_length=50)),
                ('direccion', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='publicacion',
            fields=[
                ('id_s', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('tema', models.CharField(max_length=50)),
                ('descripcion', models.CharField(max_length=50)),
                ('fecha', models.CharField(max_length=50)),
                ('resumen', models.TextField()),
            ],
        ),
    ]
